language: node_js
node_js:
  - node
notifications:
  email: false
script:
  - npm test
  - npm run build
deploy:
  provider: heroku
  api_key:
    secure: exKDaSosnd14MbYKtFG79PCXoU/+5MqUuYWJ8uP9Pb46V62XAGRCr+2f5K/PXb1nkuzAk+wNu7aBefhzenA5TE1KdoSkDpQVVNP1oH5gC7hXPpGz8HZmqezOUbuSJ/E70mbwZhID5fL/1ZjJqC1GehP20Vkobzb4JWfi/95cdkFE5tk0Lt1V0tcWaPoPJXVbVPqPrUQ5G9uBtIjQ8edJ+WytcHt2Hp6rO+g7bFtDC+4FIdpJi5bqbkPGS4N+vZlRdS7ZekQJ9d02O/j8TQMa2smWTDsXosU+GCWxxMosXqW82wBpU9/KFvYgqkGKoi7iANIXVXuz4wqfg9do7MsVw8xsQL0g25eQipTl2hCgdiUfP71t9YrnNrqO6uN5x2EmuaaI2M+kZo2CZMu2v3CGDre5FReRYqbraxbxRFYyDeA6/L7Vw8nqTbsmxeWZ7727EgoIs2XyFwm7EmygRE3swWjGD1QYqLNiDc3deyOPVs0BKZcoOFRFrv9It1Kx1ecB0zZ8tl/APxxZMdwIc5v6WsP7RS+qHxGHEroAhYeYC9ybCvzJHOLHBCz6L0VGPaSQi+l8HN3wKFonJrtZNdUBg4HeixjekielNCun7YOZB1s7dS6Y7QvGjfSE4N4ZlCOaKU2ADsiBG61D3Ccy5QJXU6WwT8PszU0f9IhRfMW3iDc=
  app: beer-by-design
  on:
    branch: main
